enable default logger config only when env var is set
CiscoDevNet/vManage-client pull request #131
Opened 2023-02-20 12:26 UTC by sbasan

Sometimes creating `vmngclient.log` in current working directory is not desired, and currently cannot be prevented.
Propose to control logging setting via env variable, which indicates that we are in "development" mode.
Added explanation in `README.md`:
### **Environmet Variables**
- **`VMNGCLIENT_DEVEL`** when set: loggers will be configured according to `./logging.conf` and `urllib3.exceptions.InsecureRequestWarning` will be suppressed

2023-02-20 12:34 UTC, tomaszwarda submitted a review, later dismissed

2023-02-20 12:36 UTC, tzietkowski approved these changes

2023-02-22 16:23 UTC, tehAgitto requested changes

2023-02-22 16:23 UTC, tehAgitto commented on README.md
> +### **Environmet Variables**
typo

2023-02-23 08:03 UTC, sbasan commented on README.md
> +### **Environmet Variables**
fixed

2023-02-24 08:26 UTC, tehAgitto approved these changes

2023-02-24 08:30 UTC, merged