Policy: Added new class for creation of centralized policy lists and vSmart policy
CiscoDevNet/vManage-client pull request #222
Opened 2023-04-24 06:33 UTC by ravindra-h

Policy: Added new class for creation of centralized policy with following API support
    - Create, get all, get details, delete
    -- Data prefix list
    -- Site list
    -- VPN list
    -- Data / traffic policy
    - Create, activate, deactivate
    -- vSmart policy
    -- vSmart CLI policy

# Pull Request summary:
Policy: Added new class for creation of centralized policy lists and vSmart policy

# Description of changes:
Added new class for creation of centralized policy with following API support
    - Create, get all, get details, delete
    -- Data prefix list
    -- Site list
    -- VPN list
    -- Data / traffic policy
    - Create, activate, deactivate
    -- vSmart policy
    -- vSmart CLI policy

# Checklist:
- [x] Make sure to run pre-commit before commiting changes
- [x] Make sure all checks have passed
- [x] PR description is clear and comprehensive
- [x] Mentioned the issue that this PR solves (if applicable)
- [x] Make sure you test the changes

2023-04-25 08:16 UTC, tehAgitto requested changes
Please re-check PR and provide the typing for variables.

2023-04-25 08:16 UTC, tehAgitto commented on vmngclient/api/policy_list.py
> +    def create_data_prefix_list(self, name: str, ip_prefixes: str):
Please define return type

2023-04-25 08:16 UTC, tehAgitto commented on vmngclient/api/policy_list.py
> +        """
There is no need to provide documentation if the method name is self-documented

2023-04-25 08:16 UTC, tehAgitto commented on vmngclient/api/policy_list.py
> +            list_id = None
```suggestion
        list_id = response.json.get("listId", None)
```

2023-04-25 08:16 UTC, tehAgitto commented on vmngclient/api/policy_list.py
> +    def get_data_prefix_lists(self):
Could you provide return type, please?

2023-04-25 08:16 UTC, tehAgitto commented on vmngclient/api/policy_list.py
> +    def get_data_prefix_list(self, name):
Could you provide return type and type for the attributes?

2023-04-25 08:16 UTC, tehAgitto commented on vmngclient/api/policy_list.py
> +    def delete_data_prefix_list(self, list_id):
Could you provide the typing, please?

2023-04-25 08:16 UTC, tehAgitto commented on vmngclient/api/policy_list.py
> +    def create_site_list(self, name: str, sites: str):
Could you provide the return type, please?

2023-04-25 08:16 UTC, tehAgitto commented on vmngclient/api/policy_list.py
> +            list_id = None
```suggestion
        list_id = response.json.get("listId", None)
```

2023-04-25 08:16 UTC, tehAgitto commented on vmngclient/api/policy_list.py
> +    def get_site_lists(self):
Could you provide the return type, please?

2023-04-25 08:16 UTC, tehAgitto commented on vmngclient/api/policy_list.py
> +    def get_site_list(self, name):
Could you provide the typing, please?

2023-09-15 16:21 UTC, sbasan commented on vmngclient/api/policy_list.py
> +    def create_data_prefix_list(self, name: str, ip_prefixes: str):
migrated to endpoints layer

2023-09-18 07:10 UTC, dariuszniedzielski-codilime approved these changes

2023-09-19 10:08 UTC, sbasan approved these changes
modelled endpoints

2023-09-19 12:10 UTC, tehAgitto approved these changes

2023-09-19 12:15 UTC, merged