[Fix] Device Specific variable usage
CiscoDevNet/vManage-client pull request #317
Opened 2023-07-18 14:32 UTC by tehAgitto

# Pull Request summary:
Small refactor & fix

2023-07-19 10:12 UTC, sbasan requested changes

2023-07-19 10:12 UTC, sbasan commented on vmngclient/api/templates/models/cisco_system.py
> +# from enum import Enum
Please remove or uncomment :)
Causes mypy `error: invalid syntax`

2023-07-19 10:12 UTC, sbasan commented on vmngclient/tests/templates/models/cisco_aaa.py
> +# type: ignore
Can we be more specific what type-check error we are ignoring?
Is it really needed for whole file?
(found also in other files)

2023-07-19 10:14 UTC, sbasan commented
To fix mypy cache error modify linting.yml
```
mkdir .mypy_cache
...
poetry run mypy --show-error-codes --show-error-context --pretty --install-types --non-interactive vmngclient --cache-dir=.mypy_cache/
```

2023-07-19 10:59 UTC, cicharka approved these changes

2023-07-26 08:52 UTC, sbasan approved these changes
lgtm

2023-07-26 08:58 UTC, merged