added migration_key changes
CiscoDevNet/vManage-client pull request #388
Opened 2023-10-13 18:24 UTC by renukavinay

# Pull Request summary:
Added the new key in migration

# Description of changes:
Added the new key in migration for mt-st migration

# Checklist:
- [ ] Make sure to run pre-commit before committing changes
- [ ] Make sure all checks have passed
- [ ] PR description is clear and comprehensive
- [ ] Mentioned the issue that this PR solves (if applicable)
- [ ] Make sure you test the changes

2023-10-16 08:32 UTC, sbasan requested changes

2023-10-16 08:32 UTC, sbasan commented on vmngclient/endpoints/tenant_migration.py
> +    def import_tenant_data(self, migrationKey, data: BinaryIO) -> ImportInfo:
Introduced parameter is not used in method body (It is not reaching vManage in any way)

2023-10-16 22:04 UTC, JimOverholt submitted a review, later dismissed

2023-10-17 17:09 UTC, JimOverholt approved these changes

2023-10-17 18:36 UTC, merged