Fix Packet capture
CiscoDevNet/vManage-client pull request #66
Opened 2022-12-15 11:46 UTC by danielui

- use bool instead string in enable data stream in basic_api
- use session get_file in download packet_capture
- add dubug logs in packet capture

2022-12-15 11:52 UTC, tehAgitto requested changes

2022-12-15 11:52 UTC, tehAgitto commented on vmngclient/api/packet_capture_api.py
> +        # return True
If not used - remove

2022-12-15 15:22 UTC, danielui commented on vmngclient/api/packet_capture_api.py
> +        # return True
Fixed

2022-12-16 02:59 UTC, JimOverholt approved these changes

2022-12-20 10:05 UTC, tehAgitto approved these changes

2022-12-20 10:06 UTC, merged